ALTER TABLE Student
ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE Mark
ALTER COLUMN student_id BIGINT NOT NULL,
ALTER COLUMN subject_id BIGINT NOT NULL,
ADD CHECK(mark >= 1 AND mark <= 10);

ALTER TABLE Subject
ADD CHECK(grade >= 1 AND grade <= 5);

ALTER TABLE PaymentType
ADD UNIQUE(name);

ALTER TABLE Payment
ALTER COLUMN type_id BIGINT NOT NULL,
ALTER COLUMN amount decimal NOT NULL,
ALTER COLUMN payment_date DateTime NOT NULL;